name: labeling-ticket-todo
on:
  issues:
    types: [labeled]
jobs:
  label_issues:
    runs-on: ubuntu-latest
    if: |
      contains(github.event.issue.labels.*.name, 'status: todo')
    permissions:
      issues: write
    steps:
      - run: 'gh issue reopen "$NUMBER"'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
